import "unknwn.idl";
import "oaidl.idl";
import "ocidl.idl";

[
uuid(2044b06d-c185-4e6e-a4c2-078a5b6f9ed0),
version(1.0)
]
interface IProcessMonitorRegistrarEx: IDispatch
{
    [id(1)] HRESULT registerProcessByName(BSTR name);
    [id(2)] HRESULT unregisterProcessByName(BSTR name);
    [id(3)] HRESULT unregisterAllNames();

    [id(4)] HRESULT pushPid(unsigned int pid);
    [id(5)] HRESULT removePid(unsigned int pid);
    [id(6)] HRESULT clearPids();

    [id(7)] HRESULT getLastError([out] unsigned int *code, [out, size_is(, *msglen)] LPBSTR msg, [out] unsigned int *msglen);
}

[
uuid(2044b06d-c185-4e6e-a4c2-078a5b6f9ed1)
]
dispinterface IProcessMonitorExDispatch
{
properties:
    [id(1)] unsigned int LastError;
    [id(2)] BSTR LastErrorMsg;

    [id(3)] unsigned int StatusPid;
    [id(4)] BSTR StatusPname;
    [id(5)] unsigned int Status;

methods:
    [id(6)] HRESULT PushPid(unsigned int pid);
    [id(7)] HRESULT RemovePid(unsigned int pid);
    [id(8)] HRESULT ClearPids();

    [id(9)] HRESULT UpdateStatuses();
    [id(10)] HRESULT GetChangedStatusFirst();
	[id(11)] HRESULT GetChangedStatusNext();

    [id(12)] HRESULT RegisterProcessByName(BSTR name);

    [id(13)] HRESULT UnregisterProcessByName(BSTR name);
    [id(14)] HRESULT UnregisterAllNames();
};

[
uuid(3ff1aab8-f3d8-11d4-825d-00194b3646c1),
version(1.0)
]
library ProcessManagerEx
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	interface IProcessMonitorRegistrarEx;
	dispinterface IProcessMonitorExDispatch;
}
