#ifndef SERVERDLLEXTEND_GLOBAL_H
#define SERVERDLLEXTEND_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERDLLEXTEND_LIBRARY)
#  define SERVERDLLEXTENDSHARED_EXPORT Q_DECL_EXPORT __stdcall
#else
#  define SERVERDLLEXTENDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERDLLEXTEND_GLOBAL_H
