#ifndef SERVEREXTENDDLL_GLOBAL_H
#define SERVEREXTENDDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVEREXTENDDLL_LIBRARY)
#  define SERVEREXTENDDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVEREXTENDDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVEREXTENDDLL_GLOBAL_H
